services:
  ClientSQL:
    container_name: ClientSQL
    image: mysql
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./ClientSQL/:/docker-entrypoint-initdb.d
    networks:
      - ClientNet
  ClientProd:
    container_name: ClientProd
    build: ./ClientProd/
    image: client_pfpm
    ports:
      - 5502:5502
    networks:
      - EONet
      - ClientNet
    depends_on: 
      ClientSQL:
        condition: service_started
  ClientCons:
    container_name: ClientCons
    build: ./ClientCons/
    image: client_ppm
    networks:
      - EONet
      - ClientNet
    depends_on: 
      ClientSQL:
        condition: service_started

networks:
  EONet:
      external: true
  ClientNet:
      external: true