services:
  OrderSQL:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./OrderSQL/:/docker-entrypoint-initdb.d
    networks:
      - OrderNet
  OrderProd:
    build: ./OrderProd/
    image: order_pfpm
    ports:
      - 5500:5500
    networks:
      - EONet
      - OrderNet
    depends_on: 
      OrderSQL:
        condition: service_started
  OrderCons:
    build: ./OrderCons/
    image: order_ppm
    networks:
      - EONet
      - OrderNet
    depends_on: 
      OrderSQL:
        condition: service_started

networks:
  EONet:
  OrderNet: