FROM python:3.10.11-slim-bullseye

WORKDIR /app
COPY ./account.py .
COPY ./account_producer.py .

RUN python -m pip install flask
RUN python -m pip install pika
RUN python -m pip install mysql-connector-python

EXPOSE 5504/tcp

CMD python -m flask --app account run --host=0.0.0.0 -p 5504
