services:
  EventSQL:
    container_name: EventSQL
    image: mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./EventSQL/:/docker-entrypoint-initdb.d
    networks:
      - EventNet
  EventProd:
    container_name: EventProd
    build: ./EventProd/
    image: event_pfpm
    ports:
      - 5501:5501
    networks:
      - EONet
      - EventNet
    depends_on: 
      EventSQL:
        condition: service_started
  EventCons:
    container_name: EventCons
    build: ./EventCons/
    image: event_ppm
    networks:
      - EONet
      - EventNet
    depends_on: 
      EventSQL:
        condition: service_started

networks:
  EONet:
  EventNet: