services:
  AccountSQL:
    image: mysql
    ports:
      - 3310:3310
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./AccountSQL/:/docker-entrypoint-initdb.d
    networks:
      - AccountNet
  AccountProd:
    build: ./AccountProd/
    image: account_pfpm
    ports:
      - 5504:5504
    networks:
      - EONet
      - AccountNet
    depends_on: 
      AccountSQL:
        condition: service_started
  AccountCons:
    build: ./AccountCons/
    image: account_ppm
    networks:
      - EONet
      - AccountNet
    depends_on: 
      AccountSQL:
        condition: service_started

networks:
  EONet:
  AccountNet: