services:
  StaffSQL:
    image: mysql
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./StaffSQL/:/docker-entrypoint-initdb.d
    networks:
      - StaffNet
  StaffProd:
    build: ./StaffProd/
    image: staff_pfpm
    ports:
      - 5501:5501
    networks:
      - EONet
      - StaffNet
    depends_on: 
      StaffSQL:
        condition: service_started
  StaffCons:
    build: ./StaffCons/
    image: staff_ppm
    networks:
      - EONet
      - StaffNet
    depends_on: 
      StaffSQL:
        condition: service_started

networks:
  EONet:
  StaffNet: